### ISSUE TITLE
Missing support for the ValidateValueCallback method of Register/RegisterAttached

### ISSUE THREAD

**Issue by CyberBotX** [IGood/boilerplatezero#17]
The subject line says it all, but basically all the forms of Register{Attached}{ReadOnly} have an overload where the final parameter is of type `ValidateValueCallback`, but boilerplatezero does not have anything in place to add that to the generated call.

**Comment by IGood** [comment]
Hello & thanks for opening this feature request.

Do you have suggestions for the expected name of methods that should be used for validation?
I'm currently working to support *only* this
```cs
IsValidFoo
```
but I can also understand making a case for things like
```cs
FooValidateCallback
ValidateFoo
```

**Comment by CyberBotX** [comment]
I think I usually see the word Validate in the name of the callbacks in code I've seen in the wild. But I'm not opposed to only supporting Valid.
