### ISSUE TITLE
error CS0102: The type 'MainWindow' already contains a definition for 'Filename'

### ISSUE THREAD

**Issue by graealex** [IGood/boilerplatezero#21]
I added a DependencyProperty to my WPF project (.NET 5.0, VS 2022) MainWindow class:

```
private static readonly DependencyPropertyKey FilenamePropertyKey = Gen.Filename<string>();
```

Visual Studio reports the following errors:

```
error CS0102: The type 'MainWindow' already contains a definition for 'FilenameProperty'
error CS0102: The type 'MainWindow' already contains a definition for 'Filename'
error CS0111: Type 'MainWindow.Gen' already defines a member called 'Filename' with the same parameter types
```

The auto-generated file looks fine:

```
partial class MainWindow
{
    public static readonly DependencyProperty FilenameProperty = FilenamePropertyKey.DependencyProperty;
    /// <summary>Gets the value of the <see cref="FilenameProperty"/> dependency property.</summary>
    public string Filename
    {
        get => (string)this.GetValue(FilenameProperty);
        private set => this.SetValue(FilenamePropertyKey, value);
    }
    private static partial class Gen
    {
        /// <summary>
        /// Registers a read-only dependency property named "Filename" whose type is <typeparamref name="__T"/>.
        /// </summary>
        public static DependencyPropertyKey Filename<__T>()
        {
            var metadata = (PropertyMetadata)null!;
            return DependencyProperty.RegisterReadOnly("Filename", typeof(__T), typeof(MainWindow), metadata, null);
        }
    }
}
```

What could be causing this? I varied types and names, and if I add a second property, I get errors for that as well. Adding Bpx.Test to my solution causes no problems, the project compiles fine.

**Comment by graealex** [comment]
Addendum:

```
private static readonly DependencyProperty FilenameProperty = Gen.Filename<string>();
```

causes similar "already contains a definition" errors. It's as if the generated code gets compiled twice.

**Comment by IGood** [comment]
Yikes! I haven't seen this problem before.
From what you've said - it does seem as if the code generation is happening 2x 🤔

Is there more information in the compiler output log? Perhaps details about file/line where each occurrence exists?

**Comment by graealex** [comment]
I have created a minimal test case that reproduces the issue:

- Create a new WPF project (.NET 5)
- Add boilerplatezero via Nuget
- Add `private static readonly DependencyProperty BlaBlaProperty = Gen.BlaBla<string>();` to MainWindow.xaml.cs
- Compile fails with mentioned errors
- Commit all to Github
- Deleted the local repo
- Cloned the repo from Github
- Opened local repo with VS.2022, click "Build" - get the same errors

The repo is here: https://github.com/graealex/BpzWpfTestNuget

**Comment by graealex** [comment]
Addendum: the same project compiles fine without any errors in:

```
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.3.0 Preview 2.0
```

**Comment by graealex** [comment]
[build.detailed.log](https://github.com/IGood/boilerplatezero/files/9337018/build.detailed.log)
[build.diag.log](https://github.com/IGood/boilerplatezero/files/9337020/build.diag.log)

Also logs to the build process when launched from command line `dotnet build --verbosity diag` and `dotnet build --verbosity detailed`

**Comment by IGood** [comment]
Thanks for providing all this great info!

I can confirm that I get errors in these versions
```
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.2.6

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.3.0 Preview 1.1
```

I'll continue investigating. This bug makes me very sad.

**Comment by IGood** [comment]
Good news!

This is a known bug with a workaround that I found here - https://github.com/dotnet/wpf/issues/6792#issuecomment-1183633402
```xml
	<Target Name="RemoveDuplicateAnalyzers" BeforeTargets="CoreCompile">
		<!-- Work around https://github.com/dotnet/wpf/issues/6792 -->
		<ItemGroup>
			<FilteredAnalyzer Include="@(Analyzer->Distinct())" />
			<Analyzer Remove="@(Analyzer)" />
			<Analyzer Include="@(FilteredAnalyzer)" />
		</ItemGroup>
	</Target>
```

**Comment by IGood** [comment]
Thank you, @graealex, for donating to support this project! You are very kind.
